server:
  log_level: info
  http_listen_port: 3103

clients:
  - url: http://loki.components.svc.cluster.local:3100/loki/api/v1/push
  # - url: http://openobserve.openobserve.svc.cluster.local:5080/api/default/waht/_json
  #   headers:
  #     Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM="
  #     Content-Type: application/json
  
positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  - job_name: kubernetes-pods
    pipeline_stages:
      - cri: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name

      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace

      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod

      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container

      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__

      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
